services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AndreasWolf\Uuid\TypoScript\ResolveUuidInTypoScriptEventListener:
    tags:
      - name: event.listener
        identifier: 'uuid'
        event: TYPO3\CMS\Core\TypoScript\AST\Event\EvaluateModifierFunctionEvent

  AndreasWolf\Uuid\Service\TableDefinitionEventListener:
    tags:
      - name: event.listener
        identifier: 'uuid-fields'
        method: 'addUuidFieldsToDatabaseSchema'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent

  AndreasWolf\Uuid\Service\TcaBuildEventListener:
    tags:
      - name: event.listener
        identifier: 'uuid-fields'
        method: 'addUuidFieldsToTca'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent

  AndreasWolf\Uuid\Service\TableConfigurationService: {}
